## Reading CSV File Using Panda

In [12]:
import pandas as pd
df = pd.read_json("titanic.json")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,None,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,None,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,None,C

## Reading EXCEL File Using Panda

In [11]:
import pandas as pd
df = pd.read_excel("Supermarket-Sales.xlsx")
df.head(10)

,Invoice ID,Customer Name,Branch,City,Customer Type,Gender,Product Line,Unit Price,Quantity,Tax 5%,Total,Date,Payment
0,839-36-2830,Arun Kumar,A,Yangon,Member,Female,Electronic accessories,47.64,2,4.76,100.04,2025-04-28,Ewallet
1,462-97-6087,Riya Joseph,B,Mandalay,Member,Female,Electronic accessories,79.09,1,3.95,83.04,2025-05-27,Credit card
2,543-45-5253,Aisha Khan,B,Mandalay,Member,Female,Home and lifestyle,49.99,10,25.00,524.90,2025-04-11,Credit card
3,630-80-8664,Meera Nair,B,Mandalay,Normal,Male,Electronic accessories,75.70,5,18.93,397.43,2025-02-27,Ewallet
4,829-42-3676,Mohan B,C,Naypyitaw,Normal,Female,Sports and travel,67.40,2,6.74,141.54,2025-04-18,Cash
5,928-67-4246,Arun Kumar,B,Mandalay,Normal,Male,Food and beverages,39.98,2,4.00,83.96,2025-05-07,Credit card
6,321-40-6608,Riya Joseph,B,Mandalay,Member,Male,Fashion accessories,63.54,5,15.88,333.58,2025-03-03,Ewallet
7,122-40-9922,Ananya Patel,B,Mandalay,Normal,Female,Home and lifestyle,79.25,8,31.70,665.70,2025-02-26,Credit card
8,383-30-5763,Harish Kumar,B,Mandalay,Normal,Female,Fashion accessories,67.57,5,16.89,354.74,2025-06-17,Ewallet
9,833-20-3574,Priya Sharma,B,Mandalay,Normal,Female,Health and beauty,32.46,10,16.23,340.83,2025-01-14,Ewallet

## Check missing values

In [16]:
import pandas as pd
df = pd.read_json("titanic.json")
print(df)
df.head()

#Check missing values
#isnull()
#used to identify missing values
print(df.isnull())
#Count missing values for all felid
df.isnull().sum()

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Check missing values for particular Col

In [21]:
import pandas as pd
df = pd.read_json("titanic.json")
print(df)
df.head()

#Check missing values
#isnull()
#used to identify missing values
print(df.isnull())
#Count missing values for all felid
df.isnull().sum()
#print Rows having Missing Age
df[df['Age'].isnull()]

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,None,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,None,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,None,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,None,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,None,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,None,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,None,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,None,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,None,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,None,S

In [23]:
import pandas as pd

# Load dataset
df = pd.read_json("titanic.json")

# Check missing values
print(df.isnull().sum())

# Print rows with missing Age values
df[df['Age'].isnull()]

# Fill Age missing values with mean
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)

# Verify missing values in Age
df['Age'].isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

np.int64(0)

In [25]:
import pandas as pd

df = pd.read_json("titanic.json")

# by using mode() means the most frequently occurring value in a column
me = df["Embarked"].mode()[0]
df['Embarked'] = df['Embarked'].fillna(me)
#dropna()
#Remove rows
df.dropna()
#remove column
df.dropna(axis = 1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,Q

In [27]:
import pandas as pd
df = pd.read_json("titanic.json")
print(df)
df.head()
# Used to identify missing values
print(df.isnull())
#count missing values for all field
df.isnull().sum()
#Find rows having missing age
df[df["Age"].isnull()]
#fill age with mean
ma = df["Age"].mean()
df["Age"] = df["Age"].fillna(ma)
# by using mode() means the most frequently occurring value in a column
me = df["Embarked"].mode()[0]
df['Embarked'] = df['Embarked'].fillna(me)
#dropna()
#Remove rows
df.dropna()
#remove column
df.dropna(axis = 1)
#you need specific row and column
print(df.iloc[0:5,1:3])
#change my index to customer id
df=pd.read_csv('customers-100.csv', index_col= 'Customer Id')
print(df)
#acessing specific columns for particular index
print(df.loc['053d585Ab6b3159', ['First Name', 'Company']])
#range from this to that
print(df.loc['cb8E23e48d22Eae': '2354a0E336A91A1', ['First Name', 'Company']])

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500  None        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250  None        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500  None        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000  None        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500  None        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500  None        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]
   Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3
                 Index First Name Last Name                          Company  \
Customer Id
DD37Cf93aecA6Dc      1     Sheryl    Baxter                  Rasmussen Group
1Ef7b82A4CAAD10      2    Preston    Lozano                      Vega-Gentry
6F94879bDAfE5a6      3        Roy     Berry                    Murillo-Perry
5Cef8BFA16c5e3c      4      Linda     Olsen  Dominguez, Mcmillan and Donovan
053d585Ab6b3159      5     Joanna    Bender         Martin, Lang and Andrade
...                ...        ...       ...                              ...
cb8E23e48d22Eae     96       Karl     Greer                        Carey LLC
CeD220bdAaCfaDf     97       Lynn  Atkinson            Ware, Burns and Oneal
28CDbC0dFe4b1Db     98       Fred    Guerra                    Schmitt-Jones
c23d1D9EE8DEB0A     99     Yvonne    Farmer               Fitzgerald-Harrell
2354a0E336A91A1    100   Clarence    Haynes               Le, Nash and Cross

                              City                     Country  \
Customer Id
DD37Cf93aecA6Dc       East Leonard                       Chile
1Ef7b82A4CAAD10  East Jimmychester                    Djibouti
6F94879bDAfE5a6      Isabelborough         Antigua and Barbuda
5Cef8BFA16c5e3c         Bensonview          Dominican Republic
053d585Ab6b3159     West Priscilla  Slovakia (Slovak Republic)
...                            ...                         ...
cb8E23e48d22Eae       East Richard                      Guyana
CeD220bdAaCfaDf       New Bradview                   Sri Lanka
28CDbC0dFe4b1Db         Ortegaland             Solomon Islands
c23d1D9EE8DEB0A    Lake Elijahview                       Aruba
2354a0E336A91A1          Judymouth                    Honduras

                                Phone 1                 Phone 2  \
Customer Id
DD37Cf93aecA6Dc            229.077.5154        397.884.0519x718
1Ef7b82A4CAAD10              5153435776        686-620-1820x944
6F94879bDAfE5a6         +1-539-402-0259     (496)978-3969x58947
5Cef8BFA16c5e3c  001-808-617-6467x12895         +1-813-324-8756
053d585Ab6b3159  001-234-203-0635x76146   001-199-446-3860x3486
...                                 ...                     ...
cb8E23e48d22Eae     (188)169-1674x58692    001-841-293-3519x614
CeD220bdAaCfaDf         +1-846-706-2218            605.413.3198
28CDbC0dFe4b1Db    +1-753-067-8419x7170   +1-632-666-7507x92121
c23d1D9EE8DEB0A           (530)311-9786  001-869-452-0943x12424
2354a0E336A91A1           (753)813-6941            783.639.1472

                                          Email Subscription Date  \
Customer Id
DD37Cf93aecA6Dc        zunigavanessa@smith.info        2020-08-24
1Ef7b82A4CAAD10                 vmata@colon.com        2021-04-23
6F94879bDAfE5a6             beckycarr@hogan.com        2020-03-25
5Cef8BFA16c5e3c     stanleyblackwell@benson.org        2020-06-02
053d585Ab6b3159         colinalvarado@miles.net        2021-04-17
...                                         ...               ...
cb8E23e48d22Eae                hhart@jensen.com        2022-01-30
CeD220bdAaCfaDf               vkemp@ferrell.com        2021-07-10
28CDbC0dFe4b1Db                swagner@kane.org        2021-09-18
c23d1D9EE8DEB0A  mccarthystephen@horn-green.biz        2021-08-11
2354a0E336A91A1          colleen91@faulkner.biz        2020-03-11

                                           Website
Customer Id
DD37Cf93aecA6Dc         http://www.stephenson.com/
1Ef7b82A4CAAD10              http://www.hobbs.com/
6F94879bDAfE5a6           http://www.lawrence.com/
5Cef8BFA16c5e3c         http://www.good-lyons.com/
053d585Ab6b3159        https://goodwin-ingram.com/
...                                            ...
cb8E23e48d22Eae            http://hayes-perez.com/
CeD220bdAaCfaDf         https://novak-allison.com/
28CDbC0dFe4b1Db              https://www.ross.com/
c23d1D9EE8DEB0A               http://watkins.info/
2354a0E336A91A1  http://www.hatfield-saunders.net/

[100 rows x 11 columns]
First Name                      Joanna
Company       Martin, Lang and Andrade
Name: 053d585Ab6b3159, dtype: object
                First Name                Company
Customer Id
cb8E23e48d22Eae       Karl              Carey LLC
CeD220bdAaCfaDf       Lynn  Ware, Burns and Oneal
28CDbC0dFe4b1Db       Fred          Schmitt-Jones
c23d1D9EE8DEB0A     Yvonne     Fitzgerald-Harrell
2354a0E336A91A1   Clarence     Le, Nash and Cross

In [28]:
import pandas as pd

# Titanic Dataset
titanic = pd.read_json("titanic.json")

print(titanic.head())

# Identify missing values
print(titanic.isnull())

# Count missing values
print(titanic.isnull().sum())

# Rows with missing Age
print(titanic[titanic["Age"].isnull()])

# Fill Age with mean
age_mean = titanic["Age"].mean()
titanic["Age"] = titanic["Age"].fillna(age_mean)

# Fill Embarked with mode
embarked_mode = titanic["Embarked"].mode()[0]
titanic["Embarked"] = titanic["Embarked"].fillna(embarked_mode)

# Remove rows with missing values
print(titanic.dropna())

# Remove columns with missing values
print(titanic.dropna(axis=1))

# iloc example
print(titanic.iloc[0:5, 1:3])

# GroupBy Operations
print("\nAverage Fare per Class")
print(titanic.groupby("Pclass")["Fare"].mean())

print("\nCount Survivors by Gender")
print(titanic.groupby("Sex")["Survived"].sum())

print("\nMultiple Aggregations")
print(
    titanic.groupby("Pclass").agg({
        "Age": ["mean", "min", "max"],
        "Fare": ["mean", "sum"]
    })
)

# Customer Dataset
customers = pd.read_csv("customers-100.csv", index_col="Customer Id")

print(customers.head())

# Access specific columns for particular index
print(
    customers.loc[
        "053d585Ab6b3159",
        ["First Name", "Company"]
    ]
)

# Range of records
print(
    customers.loc[
        "cb8E23e48d22Eae":"2354a0E336A91A1",
        ["First Name", "Company"]
    ]
)

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500  None        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250  None        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500  None        S
     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
     PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James
17            18         1       2              Williams, Mr. Charles Eugene
19            20         1       3                   Masselmani, Mrs. Fatima
26            27         0       3                   Emir, Mr. Farred Chehab
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked
5      male  NaN      0      0      330877   8.4583  None        Q
17     male  NaN      0      0      244373  13.0000  None        S
19   female  NaN      0      0        2649   7.2250  None        C
26     male  NaN      0      0        2631   7.2250  None        C
28   female  NaN      0      0      330959   7.8792  None        Q
..      ...  ...    ...    ...         ...      ...   ...      ...
859    male  NaN      0      0        2629   7.2292  None        C
863  female  NaN      8      2    CA. 2343  69.5500  None        S
868    male  NaN      0      0      345777   9.5000  None        S
878    male  NaN      0      0      349217   7.8958  None        S
888  female  NaN      1      2  W./C. 6607  23.4500  None        S

[177 rows x 12 columns]
     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
10            11         1       3
11            12         1       1
..           ...       ...     ...
871          872         1       1
872          873         0       1
879          880         1       1
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch    Ticket     Fare        Cabin Embarked
1        0  PC 17599  71.2833          C85        C
3        0    113803  53.1000         C123        S
6        0     17463  51.8625          E46        S
10       1   PP 9549  16.7000           G6        S
11       0    113783  26.5500         C103        S
..     ...       ...      ...          ...      ...
871      1     11751  52.5542          D35        S
872      0       695   5.0000  B51 B53 B55        S
879      1     11767  83.1583          C50        C
887      0    112053  30.0000          B42        S
889      0    111369  30.0000         C148        C

[204 rows x 12 columns]
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
4                             Allen, Mr. William Henry    male  35.000000
..                                                 ...     ...        ...
886                              Montvila, Rev. Juozas    male  27.000000
887                       Graham, Miss. Margaret Edith  female  19.000000
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118
889                              Behr, Mr. Karl Howell    male  26.000000
890                                Dooley, Mr. Patrick    male  32.000000

     SibSp  Parch            Ticket     Fare Embarked
0        1      0         A/5 21171   7.2500        S
1        1      0          PC 17599  71.2833        C
2        0      0  STON/O2. 3101282   7.9250        S
3        1      0            113803  53.1000        S
4        0      0            373450   8.0500        S
..     ...    ...               ...      ...      ...
886      0      0            211536  13.0000        S
887      0      0            112053  30.0000        S
888      1      2        W./C. 6607  23.4500        S
889      0      0            111369  30.0000        C
890      0      0            370376   7.7500        Q

[891 rows x 11 columns]
   Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3

Average Fare per Class
Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

Count Survivors by Gender
Sex
female    233
male      109
Name: Survived, dtype: int64

Multiple Aggregations
              Age                   Fare
             mean   min   max       mean         sum
Pclass
1       37.048118  0.92  80.0  84.154687  18177.4125
2       29.866958  0.67  70.0  20.662183   3801.8417
3       26.403259  0.42  74.0  13.675550   6714.6951
                 Index First Name Last Name                          Company  \
Customer Id
DD37Cf93aecA6Dc      1     Sheryl    Baxter                  Rasmussen Group
1Ef7b82A4CAAD10      2    Preston    Lozano                      Vega-Gentry
6F94879bDAfE5a6      3        Roy     Berry                    Murillo-Perry
5Cef8BFA16c5e3c      4      Linda     Olsen  Dominguez, Mcmillan and Donovan
053d585Ab6b3159      5     Joanna    Bender         Martin, Lang and Andrade

                              City                     Country  \
Customer Id
DD37Cf93aecA6Dc       East Leonard                       Chile
1Ef7b82A4CAAD10  East Jimmychester                    Djibouti
6F94879bDAfE5a6      Isabelborough         Antigua and Barbuda
5Cef8BFA16c5e3c         Bensonview          Dominican Republic
053d585Ab6b3159     West Priscilla  Slovakia (Slovak Republic)

                                Phone 1                Phone 2  \
Customer Id
DD37Cf93aecA6Dc            229.077.5154       397.884.0519x718
1Ef7b82A4CAAD10              5153435776       686-620-1820x944
6F94879bDAfE5a6         +1-539-402-0259    (496)978-3969x58947
5Cef8BFA16c5e3c  001-808-617-6467x12895        +1-813-324-8756
053d585Ab6b3159  001-234-203-0635x76146  001-199-446-3860x3486

                                       Email Subscription Date  \
Customer Id
DD37Cf93aecA6Dc     zunigavanessa@smith.info        2020-08-24
1Ef7b82A4CAAD10              vmata@colon.com        2021-04-23
6F94879bDAfE5a6          beckycarr@hogan.com        2020-03-25
5Cef8BFA16c5e3c  stanleyblackwell@benson.org        2020-06-02
053d585Ab6b3159      colinalvarado@miles.net        2021-04-17

                                     Website
Customer Id
DD37Cf93aecA6Dc   http://www.stephenson.com/
1Ef7b82A4CAAD10        http://www.hobbs.com/
6F94879bDAfE5a6     http://www.lawrence.com/
5Cef8BFA16c5e3c   http://www.good-lyons.com/
053d585Ab6b3159  https://goodwin-ingram.com/
First Name                      Joanna
Company       Martin, Lang and Andrade
Name: 053d585Ab6b3159, dtype: object
                First Name                Company
Customer Id
cb8E23e48d22Eae       Karl              Carey LLC
CeD220bdAaCfaDf       Lynn  Ware, Burns and Oneal
28CDbC0dFe4b1Db       Fred          Schmitt-Jones
c23d1D9EE8DEB0A     Yvonne     Fitzgerald-Harrell
2354a0E336A91A1   Clarence     Le, Nash and Cross

In [1]:
import pandas as pd

# interpolate()
# Estimate missing values.

sample = pd.DataFrame({
    'Age': [20, 25, None, 35, 40]
})

sample['Age'] = sample['Age'].interpolate()

print(sample)

    Age
0  20.0
1  25.0
2  30.0
3  35.0
4  40.0

## INNER MERGE

In [9]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

#1. INNER MERGE
inner_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="inner"
)

print(inner_merge.head())
print(inner_merge.shape)

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60
(45, 5)

## RIGHT MERGE

In [14]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

# 3. RIGHT MERGE

right_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

print(right_merge.head())

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60

## Left merge

In [12]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

#1. Left  MERGE
left_df = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

print(left_df.tail())

    Student_ID        Name Department  Maths  Python
45        1046  Student_46        CSE    NaN     NaN
46        1047  Student_47         IT    NaN     NaN
47        1048  Student_48        ECE    NaN     NaN
48        1049  Student_49        EEE    NaN     NaN
49        1050  Student_50       MECH    NaN     NaN

## Outer merge

In [13]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

outer_merge = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)
print(outer_merge.tail())

    Student_ID Name Department  Maths  Python
50        2001  NaN        NaN   75.0    80.0
51        2002  NaN        NaN   75.0    80.0
52        2003  NaN        NaN   75.0    80.0
53        2004  NaN        NaN   75.0    80.0
54        2005  NaN        NaN   75.0    80.0

## Combine Students , Marks , Contact

In [16]:
import pandas as pd

students = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact = pd.read_excel("Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

# Combine Students, Marks, and Contact

combined_data = pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

combined_data = pd.merge(
    combined_data,
    contact,
    on="Student_ID",
    how="left"
)

print(combined_data.head())
print(combined_data.shape)

   Student_ID       Name Department  Maths  Python                 Email
0        1001  Student_1        CSE   61.0    56.0  student1@college.edu
1        1002  Student_2         IT   62.0    57.0  student2@college.edu
2        1003  Student_3        ECE   63.0    58.0  student3@college.edu
3        1004  Student_4        EEE   64.0    59.0  student4@college.edu
4        1005  Student_5       MECH   65.0    60.0  student5@college.edu
(50, 6)

## Concat Column Wise

In [17]:
# 7. CONCAT COLUMN-WISE

student_basic = students[['Student_ID', 'Name']]
student_marks = marks[['Python']]

combined_cols = pd.concat(
    [student_basic, student_marks],
    axis=1
)

print(combined_cols.head())

   Student_ID       Name  Python
0        1001  Student_1      56
1        1002  Student_2      57
2        1003  Student_3      58
3        1004  Student_4      59
4        1005  Student_5      60

## Concat Row Wise

In [18]:
part1 = students.iloc[:25]
part2 = students.iloc[25:]

print(part1.shape)
print(part2.shape)

# Concat Row-Wise

combined_rows = pd.concat(
    [part1, part2],
    axis=0
)

print(combined_rows.head())
print(combined_rows.shape)

(25, 3)
(25, 3)
   Student_ID       Name Department
0        1001  Student_1        CSE
1        1002  Student_2         IT
2        1003  Student_3        ECE
3        1004  Student_4        EEE
4        1005  Student_5       MECH
(50, 3)

## Join () two datasets by using index

In [20]:
# JOIN()
# join() works using indexes

students_index = students.set_index("Student_ID")
contact_index = contact.set_index("Student_ID")

joined_df = students_index.join(contact_index)

print(joined_df.tail(10))

                  Name Department                  Email
Student_ID
1041        Student_41        CSE  student41@college.edu
1042        Student_42         IT  student42@college.edu
1043        Student_43        ECE  student43@college.edu
1044        Student_44        EEE  student44@college.edu
1045        Student_45       MECH  student45@college.edu
1046        Student_46        CSE  student46@college.edu
1047        Student_47         IT  student47@college.edu
1048        Student_48        ECE  student48@college.edu
1049        Student_49        EEE  student49@college.edu
1050        Student_50       MECH  student50@college.edu